# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 2: Arreglos uni y multidimensionales** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con arreglos uni y multidimensionales en Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Sergio: **sergio.gonzalez@unahur.edu.ar**

## **Vectores**

Declaración y modificación/acceso usando índices

In [ ]:
#primer valor columna luego columna
#qué es iterar? = recorrer algo?
v = np.zeros((3,3), int)
print(v)
v[1][1] = 20
print(v)
"""
Solo sirve para leer:
for elemento in vector


Para iterar por los indices
for indice in range(len(vector)):
for indice in reversed(range(len(vector))):

[['' '' '']
 ['' '' '']
 ['' '' '']]
[['' '' '']
 ['' '2' '']
 ['' '' '']]


Recorrido por los elementos y por los índices

In [ ]:
#nFilas, n cols = n.shape()
import numpy as np
v2 = np.array([3, 2, 5, 6, 7])

print(v2)
"""
for elemento  in v2:
  print(elemento)


for i in range(len(v2)):
    print(i, v2[i])
    v2[i] = v2[i] * 2

Si yo tengo una función que toma un array como parametro
si cambias el array por referencia (parametro) se va a cambiar en el global

V2 = V
al hacer una "copia"  en la memoria ocupa el mismo lugar en la memoria
entonces si modificas v2 o v van a cambiar los dos

def test(v:np.array) -> None:
      v[0] = 5

import copy
V2 = copy.deepcopy(v)
str en python son inmutables (no puede modificarse)
"""

M= np.zeros((3,3), int)

nFilas, nCols = M.shape
for fila in range(nFilas):
    for col in range(nCols):
      print(M[fila, col])
print(v2)


[3 2 5 6 7]
0
0
0
0
0
0
0
0
0
[3 2 5 6 7]


Notación para acceder a subvectores

Manejo de strings como vectores

### **Ejercicio 1**

Escribir una función que recibe un numero entero N y le pide al usuario que ingrese N numeros. Al final, el programa debe retornar un vector contiendo los números que fueron ingresados. Tambien debe imprimir por pantalla la suma total de los valores y el promedio. Se deben hacer funciones para resolver el promedio y la suma total.

In [ ]:
import numpy as np
def vectorDe(nrosAPedir: int) -> np.ndarray:
    """
    Propósito: Solicita al usuario una cantidad de números entera,
    construye un array con ellos e imprime la suma total y el promedio.

    Precondiciones: nrosAPedir debe ser un entero mayor a 0.

    Parámetros:
    -nrosApedir: int - Cantidad de números a ingresar.

    Tipo: Array con los números ingresados.
    """
    salida = np.zeros(nrosAPedir, int)
    for i in range(nrosAPedir):
        numero = int(input("Ingrese un número"))
        salida[i] = numero
    print(f"La suma total es {sumaTotal(salida)}")
    print(f"El promedio es {promedioTotal(salida)}")
    return salida

def promedioTotal(array: np.ndarray) -> float:
    """
    Propósito: Calcula el promedio de todos los elementos del array
    Precondiciones: El array debe contener números (int o float).
    Parámetros:
    -array: Array - Array con los elementos a promediar.
    Tipo: float
    """
    return sumaTotal(array) / len(array)

def sumaTotal(array: np.ndarray) -> float:
    """
    Propósito: Calcula la suma total de todos los elementos del array.
    Precondiciones: El array debe contener números (int o float).
    Parámetros:
    -array: Array - Array con los elementos a sumar
    Tipo: float
    """
    """
    totalSuma = 0
    for i in range(len(array)):
        totalSuma += array[i]
    """
    return np.sum(array)

### **Ejercicio 2**

Escribir una función que recibe un vector de strings y retorna otro con los mismos elementos del vector de entrada pero en orden inverso.

In [ ]:
def invertirArrayDeStrings(arrayStr: np.ndarray) -> np.ndarray:
    """
    Propósito: Describe un array de strings invertido de derecha a izquierda.
    Precondiciones: arrayStr debe ser un array de strings
    Parámetros:
    -arrayStr: Array - Array de strings a invertir
    Tipo: Array
    """
    iInver = len(arrayStr)
    arrayInver = np.zeros(len(arrayStr), '<U20')
    for i in range(len(arrayStr)):
        iInver -= 1
        arrayInver[iInver] = arrayStr[i]
    print(arrayInver)
invertirArrayDeStrings(testArray)

['bienvidio' 'adios' 'hola']


### **Ejercicio 3**

Escribir la función sumaDeVectores que recibe dos vectores de enteros del mismo tamaño y retorna otro con la suma de ambos. La suma de vectores se realiza componente a componente, segun la siguiente forma:

v<sub>1</sub> = [ v<sub>11</sub> , v<sub>12</sub> , v<sub>13</sub> , ... , v<sub>1N</sub> ]

v<sub>2</sub> = [ v<sub>21</sub> , v<sub>22</sub> , v<sub>23</sub> , ... , v<sub>2N</sub> ]

v<sub>1</sub> + v<sub>2</sub> = [ v<sub>11</sub> + v<sub>21</sub> , v<sub>12</sub> + v<sub>22</sub> , v<sub>13</sub> + v<sub>23</sub> , ... , v<sub>1N</sub> + v<sub>2N</sub> ]

In [ ]:
import numpy as np
def sumaDeVectores(vector1: np.ndarray, vector2: np.ndarray) -> np.ndarray:
     """
        Propósito: Retorna un vector resultante de la suma componente a componente de vector1 y vector2.
        Precondiciones:
        - vector1 y vector2 deben ser arrays de enteros del mismo tamaño.
        Parametros:
        -vector1: Array - Primer vector de enteros.
        -vector2: Array - Segundo vector de enteros.
        Tipo: Array
     """
     resultadoVector = np.zeros(len(vector1), int)
     for i in range(len(vector1)):
        resultadoVector[i] = vector1[i] + vector2[i]
     print(resultadoVector)
     return resultadoVector
sumaDeVectores([1, 2, 3], [3, 2, 1])

[4 4 4]


### **Ejercicio 4**

Escribir una función que recibe un vector y desplaza todos sus elementos una posición hacia la derecha: el primero pasa a ser el segundo, el segundo pasa a ser el tercero y así sucesivamente. El último pasa a ser el primero.

Por ejemplo:

v1 = [2, 4, 1, 5, 7, **9**]

**desplazarADerecha(v1)**

=> v1 = [**9**, 2, 4, 1, 5, 7]

In [ ]:
import numpy as np
def desplazarADerecha(vector: np.ndarray) -> np.ndarray:
    """
       Propósito: Retorna un vector con todos los elementos desplazados un lugar
       a la derecha.
       Precondiciones: Ninguno
       Parámetros:
       -vector: array - Vector a desplazar
       Tipo: array
    """
    vector = np.array(vector) #asegura que se una array
    print("Original:", vector)
    resultado = np.zeros(len(vector), vector.dtype) # mantiene el tipo original
    resultado[0] = vector[-1]
    for i in range(0, len(vector) - 1):
        resultado[i + 1] = vector[i]
    return resultado
desplazarADerecha(["hola", "joao", "adios"])

Original: ['hola' 'joao' 'adios']


array(['adios', 'hola', 'joao'], dtype='<U5')

### **Ejercicio 5**

Desarrollar una función que inserte un elemento en una posición en un vector. Al insertar el elemento, se debe producir un desplazamiento a la derecha de todos los elementos en las posiciones siguientes, el último elemento se pierde.

Por ejemplo:

v1 = [2, 4, 1, 7, 6, 2]

**insertar(v1, 5, 3)** #insertamos un 5 en la posición 3

=> v1 = [2, 4, 1, **5**, 7, 6]

In [ ]:
import numpy as np
def desplazarADerecha(vector: np.ndarray) -> np.ndarray:
    """
       Propósito: Retorna un vector con todos los elementos desplazados un lugar
       a la derecha.
       Precondiciones: Ninguno
       Parámetros:
       -vector: array - Vector a desplazar
       Tipo: array
    """
    vector = np.array(vector) #asegura que se una array
    resultado = np.zeros(len(vector), vector.dtype) # mantiene el tipo original
    resultado[0] = vector[-1]
    for i in range(0, len(vector) - 1):
        resultado[i + 1] = vector[i]
    return resultado


def insertarElemento(vector, elem, i) -> np.ndarray:

    resultado = np.array(vector, type(elem))
    resultado = desplazarADerecha(vector)
    resultado[i] = elem
    return resultado
insertarElemento([1, 2, 3, 4], 0, 3)

[1 2 3 4]
[4 1 2 3]


array([4, 1, 2, 0])

### **Ejercicio 6**

Escribir una función que elimine el elemento que ocupa una determinada posición de un vector. Al eliminar, los elementos a la derecha del eliminado, deben desplazarse a la izquierda un lugar y agregar un cero en la última posición.

Por ejemplo:

v1 = [4, 3, **5**, 8, 6, 7]

**eliminar(v1, 2)** #eliminamos el elemento de la posicion 2

=> v1 = [4, 3, **8, 6, 7, 0**]

In [ ]:
def eliminarElemEnVector(vector: np.ndarray, pos: int) -> np.ndarray:
    """
    Propósito: Retorna un nuevo vector con el elemento en la posición 'pos' eliminado.
    Los elementos posteriores se desplazan a la izquierda y se coloca un 0 al final.
    Precondiciones: Ninguno
    Parámetros:
    -vector: Array -  Vector original.
    -pos: int - Posición del elemento a eliminar.
    Tipo: Array
    """
    # Asegurar que el vector es un array de NumPy
    if not isinstance(vector, np.ndarray):
        vector = np.array(vector)

    # Verificar que la posición sea válida
    if pos < 0 or pos >= len(vector):
        raise IndexError("La posición está fuera del rango del vector.")

    # Hacer una copia para no modificar el original
    copia = vector.copy()

    # Desplazar elementos a la izquierda desde la posición
    for i in range(pos, len(copia) - 1):
        copia[i] = copia[i + 1]

    # Colocar 0 en la última posición
    copia[-1] = 0

    return copia

eliminarElemEnVector([4, 3, 5, 8, 6, 7], 2)

array([4, 3, 8, 6, 7, 0])

### **Ejercicio 7**

Escribir una función que elimine todas las apariciones de un determinado elemento de un vector. Al eliminar se deben insertar tantos ceros al final como elementos se eliminaron.

Por ejemplo:

arr1 = [4, 3, 5, 8, 6, 5, 7, 5]

**eliminarApariciones(arr1, 5)** #eliminamos todos los 5 del arreglo

=> arr1 = [4, 3, 8, 6, 7, **0, 0, 0**]

In [ ]:
import numpy as np
from typing import Any
def validarTipoDeDato(variable: Any, nombre: str, tipo: type) -> Any:
    """
    Purpose: Valida que la variable sea de tipo de dato especificado.
    Precondiciones: Ninguno

    Parameters:
    -variable: any - Indica la variable a validar
    -nombre: str - Indica el nombre de la variable
    -tipo: type - Indica el tipo a esperar de variable

    Returns:
    -Any: - La misma variable si es el tipo de dato especificado.

    Raises:
    -TypeError: Si la variable no es del tipo especificado
    """
    if isinstance(variable, tipo):
        return variable
    else:
        raise TypeError(f"La variable {nombre} debeser de tipo {tipo}")

def convertirEnArraySiEsNecesario(vector: np.ndarray) -> np.ndarray:
    """
    Purpose: Convierte el vector en array si es necesario.
    Preconditions: Ninguno
    Parameters:
    -vector: np.ndarray - El vector a convertir si es necesario
    Returns: np.ndarray
    """
    if not isinstance(vector, np.ndarray):
        vector = np.array(vector)
        return vector
    return vector

def eliminarElemEnVector(vector: np.ndarray, pos: int) -> np.ndarray:
    """
    Propósito: Retorna un nuevo vector con el elemento en la posición 'pos' eliminado.
    Los elementos posteriores se desplazan a la izquierda y se coloca un 0 al final.
    Precondiciones: Ninguno
    Parámetros:
    -vector: Array -  Vector original.
    -pos: int - Posición del elemento a eliminar.
    Tipo: Array
    """
    # Asegurar que el vector es un array de NumPy
    if not isinstance(vector, np.ndarray):
        vector = np.array(vector)

    # Verificar que la posición sea válida
    if pos < 0 or pos >= len(vector):
        raise IndexError("La posición está fuera del rango del vector.")

    # Hacer una copia para no modificar el original
    copia = vector.copy()

    # Desplazar elementos a la izquierda desde la posición
    for i in range(pos, len(copia) - 1):
        copia[i] = copia[i + 1]

    # Colocar 0 en la última posición
    copia[-1] = 0

    return copia

def eliminarTodosLosElemEnVector(vector: np.ndarray, elem: any) -> np.ndarray:
    """
    Purpose: Elimina todos los elementos repetidos "elem" en el vector "vector".
    Preconditions: Ninguno.
    Parameters:
    - vector: np.ndarray - Indica el vector a modificar.
    - elem: any - Indica el tipo de elemento a eliminar del vector
    Returns:
    - np.ndarray: Nuevo vector sin las ocurrencias del elemento especificado.
    """
    #Asegura que el vector es un array
    vector = convertirEnArraySiEsNecesario(vector)
    #Hacer una copia para no modificar el original
    copy = vector.copy()
    i = 0
    while i < len(copy):
        if copy[i] == elem:
            copy = eliminarElemEnVector(copy, i)
        else:
            i += 1
    return copy

"""
    for i in range(len(copy)):
        if copy[i] == elem:
            copy[i] = 0
            copy = eliminarElemEnVector(copy, i)

    return copy
"""
eliminarTodosLosElemEnVector([2, 5, 5], 5)


array([2, 0, 0])

### **Ejercicio 8**

Escribir un procedimiento que reciben un vector y:
- Imprime un subvector con los dos primeros elementos.
- Imprime un subvector con los tres últimos elementos.
- Imprime un subvector con los elementos desde la posiciones 2 hasta la 5
- Imprime un subvector con los elementos alternados cada dos. Por ej.: v1 = [2 , 1 , 4 , 5 , 2 , 7 , 9] debería imprimir [2 , 4 , 2 , 9]

Nota: Se debe utilizar la notacion **vector [ pos<sub>inicio</sub> : pos<sub>fin</sub> : paso ]**

In [ ]:
import numpy as np

def convertirEnArraySiEsNecesario(vector: np.ndarray) -> np.ndarray:
    """
    Purpose: Convierte el vector en array si es necesario.
    Preconditions: Ninguno
    Parameters:
    -vector: np.ndarray - El vector a convertir si es necesario
    Returns: np.ndarray
    """
    if not isinstance(vector, np.ndarray):
        vector = np.array(vector)
        return vector
    return vector

def imprimirSubvector(vector: np.ndarray) -> None:
  """
  Purpose: Imprime multiples subvectores del vector  indicado.
  Preconditions: Ninguno
  Parameters:
  - vector: np.ndarray - El vector a imprimir sus subvectores.
  Tipo: None
  Returns: None
  """
  vector = convertirEnArraySiEsNecesario(vector)
  copy = vector.copy()
  print(copy[0: 2])
  print(copy[len(copy) - 3 : len(copy)])
  print(copy[2 : 5])
  print(copy[0 : -1 : 2])

imprimirSubvector([1, 2 ,3 , 4, 5, 6])

[1 2]
[4 5 6]
[3 4 5]
[1 3 5]


## **Matrices**

**Declaración** de matrices y acceso/modificación usando índices

In [ ]:
import numpy as np

vector = np.array([2, 4, 5, 6, 6])
matrix = np.array([[2, 3, 4],
                   [2, 1, 1]])

TypeError: reshape() missing 1 required positional argument: 'newshape'

Recorrido por los elementos

In [ ]:
for i in array:
    print(i)

Recorrido por las posiciones

In [ ]:
for i in range(len(array)):
    print(i)

Notación para acceder a submatrices

In [ ]:
for i in range(len(array)):
    for e in range(array[i]):
        print(e)

### **Ejercicio 12**

Escribir una función que recibe las dimensiones y retorna una matriz rellena de la siguiente forma: En la posición ( n , m ) debe contener n + m.

Por ejemplo:

mat1 = rellenaMatriz(4,3)

=> mat1 =

| <!--   --> |Col 0|Col 1|Col 2|
|------------|:---:|:---:|:---:|
| **Fila 0** |  0  |  1  |  2  |
| **Fila 1** |  1  |  2  |  3  |
| **Fila 2** |  2  |  3  |  4  |
| **Fila 3** |  3  |  4  |  5  |

In [16]:
import numpy as np
def matrizRellena(filas: int, columnas: int) -> np.ndarray:
    """
    Purpose: Retorna una matriz de NumPy donde cada elemento representa la suma de
    sus índices de fila y columna.
    Preconditions:
    - filas y columnas deben ser enteros mayores o iguales a cero.
    Parameters:
    - filas: int - Indica la cantidad de filas de la matriz
    - columnas: int - Indica la cantidad de columnas en la matriz
    Returns: np.ndarray
    """
    matrizFinal = np.zeros([filas, columnas], object)
    print(matrizFinal)
    for i in range(len(matrizFinal)):
        print(matrizFinal[i])
        for e in range(len(matrizFinal[i])):
            matrizFinal[i][e] = i + e
    return matrizFinal
matrizRellena(2, 4)

[[0 0 0 0]
 [0 0 0 0]]
[0 0 0 0]
[0 0 0 0]


array([[0, 1, 2, 3],
       [1, 2, 3, 4]], dtype=object)

### **Ejercicio 13**

Escribir una función que recibe una matriz cuadrada (N x N) y calcula la suma de los elementos que están por encima de la diagonal principal (excluyendo la diagonal).

En el ejemplo de la imagen, la función deberia retornar: *b + c + f*

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-07-29-a-les-13.18.05-1.png)

In [24]:
import numpy as np

def convertirEnArraySiEsNecesario(array: np.ndarray) -> np.ndarray:
    """
    Purpose: Convierte en un array si es necesario.
    Preconditions: Ninguno
    Parameters:
    -array: np.ndarray - El array a convertir si es necesario
    Returns: np.ndarray
    """
    if not isinstance(array, np.ndarray):
        array = np.array(array)
        return array
    return array

def sumarMatrizExcluyendoDiagonal(matriz) -> float:
    """
    Purpose: Retorna la suma de la matriz correspondiente excluyendo su diagonal.
    Preconditions: La "matriz" debe ser cuadrada
    Parameters:
    - matriz: np.ndarray - Matriz a calcular.
    Returns:
    -float
    """
    matriz = convertirEnArraySiEsNecesario(matriz)
    resultadoSuma = 0
    for i in range(len(matriz)):
        for e in range(len(matriz[i])):
            if i != e:
                resultadoSuma += matriz[i][e]
    return resultadoSuma

sumarMatrizExcluyendoDiagonal([[1,5,5,5],
                               [5,1,5,5],
                               [5,5,1,5],
                               [5,5,5,1]])

np.int64(60)

### **Ejercicio 14**

Escribir una función que retorna *True* si una matriz cuadrada es matriz diagonal y *False* en caso contrario.

Una matriz cuadrada diagonal es una matriz que tiene ceros en todos sus elementos, menos en la diagonal principal (No importan los elementos de la diagonal principal, pueden ser cero o no).

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es diagonal si:**

**M [ i , j ] == 0 para todo i != j**

Matriz diagonal de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  0  |  0  |  0  |  0  |
| **Fila 1** |  0  |  2  |  0  |  0  |
| **Fila 2** |  0  |  0  |  4  |  0  |
| **Fila 3** |  0  |  0  |  0  |  0  |

### **Ejercicio 15**

Escribir una función que retorna *True* si una matriz cuadrada de enteros es simétrica y *False* en caso contrario.

Una matriz simétrica es como la de la imagen (no importan los elementos de la diagonal principal):

![texto alternativo](https://economipedia.com/wp-content/uploads/Captura-de-Pantalla-2019-09-23-a-les-15.58.25.png)

Es decir:

**Si i, j son los índices de las filas y columnas de M**

**=> Una matriz M es simétrica si:**

**M [ i , j ] == M[ j, i ] para todo i != j**

Matriz simétrica de 4 x 4:

| <!--   --> |Col 0|Col 1|Col 2|Col 3|
|------------|:---:|:---:|:---:|:---:|
| **Fila 0** |  2  |  1  |  0  |  5  |
| **Fila 1** |  1  |  2  |  9  |  7  |
| **Fila 2** |  0  |  9  |  0  |  8  |
| **Fila 3** |  5  |  7  |  8  |  4  |

### **Ejercicio 16**

Una de las aplicaciones de matrices en programación es la representación y procesamiento de imágenes. Vamos a ver algunas cosas que se pueden hacer. Para esto primero tenemos que cargarnos una imagen en el colab y generar una matriz a partir de ella.

- Descarguen el archivo "felix.csv" del siguiente link:
https://drive.google.com/file/d/10Du9ECx7Cz-aHXQpYaWjkaAn6wKJSArn/view?usp=sharing
- Suban el archivo "felix.csv" al "colab" para poder cargarlo con el programa de Python de abajo (haciendo click en el icono de la carpeta ![texto alternativo](https://i.ibb.co/jzqwMsc/carpeta.png), de arriba a la izquierda y luego en "Subir")
- Completen el programa, procesando a la imagen guardada en la matriz "felix" para obtener las imágenes de la siguiente figura (La "A" es la imagen original), pueden hacer funciones que generen cada transformación en la imagen:

![texto alternativo](https://i.ibb.co/VvJBMsF/felix-results.png)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import copy as cp

###Lectura del archivo en la matriz#####
felix = np.genfromtxt('felix.csv', delimiter=',')
########################################
print("Cantidad de pixeles:"," x ".join(map(str,felix.shape)))
######Para mostrar matriz como imagen###########
plt.imshow(felix, cmap='Greys')
plt.show()
########################################
print(felix[0:50,0:50])