# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 6: Diccionarios** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con la estructura de datos **Diccionario** basado en el conjunto de Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Sergio: **sergio.gonzalez@unahur.edu.ar**

Declaracion de conjuntos e inserción de elementos

In [ ]:
#arreglos homogenios
#lista heterogenea
conjunto = set()
conjunto.add(3);conjunto.add(8);conjunto.add("casa")
print(conjunto)
conjunto.remove(3)
print(conjunto)
for dato in conjunto:
    print(dato)

{8, 'casa', 3}
{8, 'casa'}
8
casa


Declaración y manejo de tuplas

In [ ]:
tupla  = (2,3,4)
print(tupla)

tupla2 = ([2,3,4],5,6)
tupla2[0].append(10)
print(tupla2)


(2, 3, 4)
([2, 3, 4, 10], 5, 6)


### **Ejercicio 1**

Implementar el TDA **Diccionario (Map)**, con las siguientes operaciones (Solo lo tienen que usar, ya esta implementado por nosotros, pero repasen el funcionamiento):
- Crear (**\_\_init__()**).
- **\_\_repr__()**: Para poder imprimir por consola.
- **insertar(clave, significado)**: Inserta el par **<clave , significado>**, si la clave ya existe no debe modificar el diccionario.
- **Asignación con "dicc[clave] = significado"**: Permite modificar significados de claves existentes y agregar nuevos pares. Esto se realiza implementado la función **\_\_setitem__()**.
- **get(clave)**: Recibe una clave y retorna su significado, si la clave no existe lanza una excepción.
- **Obtener con "dicc[clave]"**: Similar a **get**, pero con el operador **"[ ]"**. Esto se realiza implementando la función **\_\_getitem__()**.
- **len()**: Retorna la cantidad de pares **<clave , significado>** en el diccionario.
- **getKeys()**: Retorna lista con claves.
- **getValues()**: Retorna lista con significados.
- **Operador "in"**: Permite la búsqueda dentro del diccionario por las claves, es decir podemos hacer **"if clave in diccionario"**.
- **remove(clave)**: Elimina el par clave-significado que contiene la clave que recibe como parámetro
- **clone()**: Genera nuevo diccionario con el mismo contenido
- **clear()**: Vacia diccionario

Si quieren iterar el diccionario deben hacer (por ejemplo para imprimir todos los pares clave-significado en diferentes lineas):

    
    for clave in diccionario.keys():
        print(clave, diccionario.get(clave))

O el equivalente con el operador **"[ ]"**:


    for clave in diccionario.keys():
        print(clave, dicionario[clave])

Aunque tengamos el operador **"in"** este sirve solo para búsquedas y no para iterar en diccionario, entonces no se puede hacer:


    for clave in diccionario:








In [1]:
import copy as cp

class Diccionario:
  #######TDA tupla clave-significado#########################
  class __TuplaDic:
    def __init__(self, key, value):
      self.__data = (key,value)

    def __repr__(self):
      return str(self.__data)

    def __eq__(self, key): # sobrecargar el numerador "==", compara las key y no los value.
      return self.__data[0] == key

    def __hash__(self): # metodo necesario para asociar claves con valores
      return hash(self.__data[0])

    def getKey(self): # devuelve la key
      return self.__data[0]

    def getValue(self): # devuelve el valor
      return self.__data[1]
  ############################################################

  ###Constructor recibe dos listas de claves y significados en orden
  def __init__(self, keys = None, values = None):
    self.__diccionario = set()
    if keys != None:
      if len(keys) == len(values):
        for i in range(len(keys)):
          self[keys[i]] = values[i]
      else:
        raise Exception("Las listas de pares clave-significado deben tener la misma cantidad")

  def __repr__(self):
    return str(self.__diccionario)

  ###Asignacion usando [], se recibe clave entre corchetes / Permite reemplazar aunque exista la clave
  def __setitem__(self, key = None, value = None):
    if key != None:
      if key in self:
        self.__diccionario.remove(key)
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###No inserta si existe la clave, es decir, si la clave existe en el dicc no modifica el valor
  def insert(self, key = None, value = None):
    if key != None:
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###Elimina si existe la clave, es decir, si la clave existe en el dicc elimina el par clave-valor
  ###Sino existe la clave, no hace nada
  def remove(self, key):
    if key in self:
        valor = self[key]
        self.__diccionario.remove(key)
        return valor

  ###Vacia dicc
  def clear(self):
    self.__diccionario = set()

  ###Clonar dicc
  def clone(self):
    return cp.deepcopy(self)

  ###Acceso a valores usando [], se recibe clave entre corchetes
  def __getitem__(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna valor de la clave que se recibe por parametro
  def get(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna lista con claves
  def keys(self):
    return [x.getKey() for x in self.__diccionario]

  ###Retorna lista con valores
  def values(self):
    return [x.getValue() for x in self.__diccionario]

  ###Operador "in"
  def __contains__(self, key):
    flag = False
    for tupla in self.__diccionario:
        if tupla.getKey() == key:
            flag = True
            break
    return flag

  ###Tamaño de diccionario
  def len(self):
    return len(self.__diccionario)

Uso de diccionarios

In [ ]:
diccionario1 = Diccionario()
diccionario1.insert(3, "auto")
diccionario1.insert(2, "casa")
diccionario1.insert(2, "perro")
print(diccionario1)
diccionario1.remove(2)
print(diccionario1)

{(2, 'casa'), (3, 'auto')}
{(3, 'auto')}


In [ ]:
diccionario1[4] = "moto"
print(diccionario1)

{(3, 'auto'), (4, 'moto')}


In [ ]:
diccionario1.get(3)
#Son iguales
diccionario1[3]
print(3 in diccionario1)


In [ ]:
print(diccionario1)
for clave in diccionario1.keys():
    print(clave)


Listas como significado

### A partir del **Ejercicio 2** vamos a trabajar **fuera del TDA Diccionario** usando la interface que creamos en el **Ejercicio 1**. Es decir,se pueden usar solo las operaciones de la interface, no se puede acceder a los componentes internos del TDA. Si necesitan estructuras auxiliares, pueden usar cualquiera de las estructuras que vimos hasta ahora: Arreglos, Listas, Pilas, Colas, Diccionarios.

### **Ejercicio 2**

Escribir un programa que declare un Diccionario de **<entero , entero>** (clave entero y significado entero) y le agrege 4 pares. Luego debe mostrar el diccionario por pantalla y su tamaño.

Finalmente, redefinir 2 significados y volver a imprimir.

In [ ]:
dic1 = Diccionario()
dic1.insert(1, 10); dic1.insert(2, 20); dic1.insert(3, 30); dic1.insert(4, 40)
print(dic1)
dic1[3] = 60
dic1[4] = 80
print(dic1)

{(1, 10), (2, 20), (3, 30), (4, 40)}
{(1, 10), (2, 20), (3, 60), (4, 80)}


### **Ejercicio 3**

Escribir un diccionario con sinónimos. Luego intentar insertar dos pares **<clave , significado>** con claves **repetidas** con la operacion **insert** y ver que sucede.

In [ ]:
dicSinonimos = Diccionario((23, 45), (10,10))
print(dicSinonimos)

{(45, 10), (23, 10)}


In [ ]:
palabras = ["casa", "perro", "computadora"]
sinonimos = ["hogar", "can", "ordenador"]
"""
otra forma de cargar en el dic:
Diccionario([1,2], ["casa", "torre"])
"""
dic__Sinonimos = Diccionario(keys = palabras, values = sinonimos)
print(dic__Sinonimos)
print("-"*70)
dic__Sinonimos["casa"] = "casita"
dic__Sinonimos.insert('computadora' , 'PC')
print(dic__Sinonimos)

{('casa', 'hogar'), ('perro', 'can'), ('computadora', 'ordenador')}
----------------------------------------------------------------------
{('casa', 'casita'), ('perro', 'can'), ('computadora', 'ordenador')}


### **Ejercicio 4**

Escribir una función que dado una lista de enteros me devuelve otra(no necesariamente en el mismo orden) sin los numeros repetidos.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Lista de salida = [1 , 3 , 2, 4]

In [ ]:
def eliminarRepetidos(lista) -> list:
  dicAux = Diccionario(lista, lista)
  sinRepetidos = dicAux.keys()
  return sinRepetidos
lista_de_entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]
lista_de_salida = eliminarRepetidos(lista_de_entrada)

print(lista_de_salida)

[1, 2, 3, 4]


### **Ejercicio 5**

Rehacer le ejercicio 4 pero retornando un diccionario en lugar de una lista.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Diccionario de salida = { (1 , None) , (3 , None) , (4 , None) , (2 , None) }

In [ ]:
def eliminarRepetidos(unaLista) -> dict:
  auxDic = Diccionario()
  for numero in unaLista:
    auxDic.insert(numero, None)
  return auxDic
listaEntrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

print(eliminarRepetidos(listaEntrada))

{(1, None), (2, None), (3, None), (4, None)}


### **Ejercicio 6**

Escribir una función que recibe una lista de números como parámetro y devuelve un diccionario con los números de la lista como claves y la cantidad de apariciones de cada uno como su significado.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 2) , (2 , 3) , (5 , 1) }

In [ ]:

def contarOcurrencias(unaLista) -> dict:
  dicSalida = Diccionario()
  for numero in unaLista:

    if numero in dicSalida:
      dicSalida[numero] = dicSalida[numero] + 1
    else:
      dicSalida.insert(numero, 1)
  return dicSalida

print(contarOcurrencias([1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]))



{(1, 3), (2, 3), (3, 2), (4, 2), (5, 1)}


### **Ejercicio 7**

Escribir una función que recibe dos diccionarios y devuelve otro con la mezcla de los dos, para las claves repetidas, se queda con los significados de primer diccionario.

Por ejemplo:

Diccionario de entrada 1 = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) }

Diccionario de entrada 2 = { (10 , 3) , (3 , 5) , (2 , 30) , (8 , 1) , (9 , 3) }

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) , (10 , 3) , (8 , 1) , (9 , 3) }

In [ ]:
def mezclarDiccionarios(primerDiccionario, segundoDiccionario) -> dict:
  diccionario_final = primerDiccionario.clone() #Instancio mi diccionario de salida como clon del primer diccionario. Esto lo hago porque me piden que en caso de que se repita alguna key, conserve el valor del primer diccionario. Clonando me aseguro que pase esto por la cosntrucción propia del diccionario
  for key in segundoDiccionario.keys(): #Para cada key entre las keys de mi segundo diccionario:
    diccionario_final.insert(key , segundoDiccionario[key]) #Voy a insertar en mi diccionario final (clon del primer diccionario) la key y el valor correspondiente. En caso que esté repetida, no hace naad

  return diccionario_final
diccionarioentrada1 = Diccionario([1 , 3 , 4 , 2 , 5] , [3 , 2 , 4 , 3 , 1])
diccionarioentrada2 = Diccionario([10 , 3 , 2 , 8 , 9] , [3 , 5 , 30 , 1 , 3])
diccionario_salida = mezclarDiccionarios(diccionarioentrada1 , diccionarioentrada2)

print(diccionario_salida)

{(1, 3), (2, 3), (3, 2), (4, 4), (5, 1), (8, 1), (9, 3), (10, 3)}


### **Ejercicio 8**

Escribir una función que modele el problema de administrar las materias que cursa un alumno.
Es decir que reciba un diccionario, un alumno y una materia y agregue esa materia a las materias que cursa.

**Nota: La lista de materias de cada alumno no debe tener materias repetidas.**

Por ejemplo:

Diccionario = { ( "Alumno1" , ["Materia1" , "Materia2"] )   ,   ( "Alumno2", [ "Materia2" , "Materia3" , "Materia4" ] ) }


In [ ]:
def agregaMaterias(diccionarioMaterias:Diccionario , alumno:str , materia:str)->Diccionario: #Defino una función que toma un diccionario de alumnos y materias, un alumno y una materia:
  if alumno in diccionarioMaterias.keys(): #Si mi alumno ya aparece en mi diccionario:
    if materia not in diccionarioMaterias[alumno]: #Y además esa materia NO ESTÁ dentro de las materias que tiene ese alumno (donde alumno es la key y el value es un array de materias)
      diccionarioMaterias[alumno].append(materia) #Appendeo la materia a las materias que cursa el alumno (modifico el value)
    else: #Sino, es decir, si la materia ya se encuentra dentro de las materias que tiene asignadas el alumno:
      raise Exception(f'{alumno} ya está asignado a la materia {materia}') #Lanzo una excepción, el alumno ya tiene esa materia asignada
  else: #Sino, es decir, que el alumno NO aparece entre los que ya están en el diccionario
    diccionarioMaterias.insert(alumno , [materia]) #Agrego al alumno y a su correspondiente materia como un nuevo par key - value:

  return diccionarioMaterias #Retornamos el diccionario de entrada, modificado

diccionarioMaterias = Diccionario(['Alumno1' , 'Alumno2'] , [['Materia1' , 'Materia2'] , ['Materia2' , 'Materia3' , 'Materia4']])
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'ALUMNX3' , 'MATERIA 5')
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'Alumno1' , 'Materia3')
print(diccionarioMaterias)

{('Alumno1', ['Materia1', 'Materia2']), ('Alumno2', ['Materia2', 'Materia3', 'Materia4'])}
{('Alumno1', ['Materia1', 'Materia2']), ('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('ALUMNX3', 'MATERIA 5')}
{('Alumno1', ['Materia1', 'Materia2', 'Materia3']), ('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('ALUMNX3', 'MATERIA 5')}


### **Ejercicio 9**

Escribir una función listaToDic que recibe una lista con chirimbolos y devuelve un diccionario con cada chirimbolo como clave y como significado una matriz de nxn donde n es la cantidad de veces que aparece el chirimbolo en la lista. La matriz se debe llenar con el chirimbolo de la clave.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares. Si es necesario definir funciones auxiliares.
Ejemplo:

```
lista = [‘*’, ‘#’, ‘/’, ‘*’, ‘#’, ‘/’, ‘*’, ‘$’]
listaToDic(lista) –> Diccionario
Entonces, listaToDic(lista) =>
{(‘*’,  [[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’]]) , (‘$’ , [[‘$’]]), (‘/’ , [[‘/’,‘/’],[‘/’,‘/’]]) , (‘#’ , [[‘#’,‘#’],[‘#’,‘#’]])}
```

Ayuda: Se recomienda generar primero la matriz con ceros y luego reemplazarlos o bien utilizar la funcion np.full(...).

In [ ]:
def listToDic(unaLista) -> dict:
    dictFinal = Diccionario()
    for chirimbolo in unaLista:
        NroApariciones = cantOcurrencias(unaLista, chirimbolo)
        dictFinal.insert(chirimbolo, [chirimbolo * NroApariciones] * NroApariciones)
    return dictFinal

def cantOcurrencias(unaLista, unElemento):
    contador = 0
    for elem in unaLista:
        if elem == unElemento:
            contador += 1
    return contador
chirimbolos = ['*', '#', '/', '*', '#', '/', '*', '$']
chirimbolos_to_dic = listToDic(chirimbolos)
print(chirimbolos_to_dic)


{('#', ['##', '##']), ('/', ['//', '//']), ('*', ['***', '***', '***']), ('$', ['$'])}


### **Ejercicio 10**

Escribir la función promedios que recibe una lista de materias (strings) y una lista de notas (enteros) del mismo tamaño. Retorna un diccionario que posee como clave cada materia y como significado su nota promedio.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares.
Por ejemplo:


listaMaterias = [“Intro Prog”, **“Objetos”**, “Estructura de Datos”, “Intro Prog”, ”Inglés”, **“Objetos”**, “Estructura de Datos”]

listaNotas = [4, **4**, 4, 6, 7, **6**, 6]

dic  = promedios(listaMaterias , listaNotas)

Entonces, dic = { (“Intro Prog”, 5) , (“Estructura de Datos”,  5) , (”Inglés”, 7) , ( “Objetos”, 5) }

In [ ]:
def cantOcurrencias(unaLista, unElemento):
    contador = 0
    for elem in unaLista:
        if elem == unElemento:
            contador += 1
    return contador

def promedios(listaDeMaterias: str, listaDeNotas: int) -> dict:
    dictResultado = Diccionario()
    for i in range(len(listaDeMaterias)):
        materia = listaDeMaterias[i]
        nota = listaDeNotas[i]
        if materia in dictResultado:
            dictResultado[materia] = (dictResultado[materia] + nota )
        else:
            dictResultado.insert(materia, nota)

    for key in dictResultado.keys():
        dictResultado[key] = dictResultado[key] / cantOcurrencias(listaDeMaterias, key)
    return dictResultado
listaMaterias = ["Intro Prog", "Objetos", "Estructura de Datos", "Intro Prog", "Inglés", "Objetos", "Estructura de Datos"]
listaNotas = [4, 4, 4, 6, 7, 6, 6]

promedios(listaMaterias , listaNotas)

{('Estructura de Datos', 5.0), ('Objetos', 5.0), ('Intro Prog', 5.0), ('Inglés', 7.0)}

### **Ejercicio 11**

Tenemos un diccionario del tipo **<Entero , Lista de enteros>** (clave número entero, significado lista de enteros) que dado un numero **X**, guarda las posibles combinaciones de ese número con otros.

Escribir una función que recibe un diccionario de este tipo y devuelve una lista con los posibles pares de números (en formato de tupla).

Por ejemplo:

Diccionario de entrada = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }

Lista de salida = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]



In [ ]:
def combinacionesDe(unDiccionario: dict) -> list:
    listaResultado = []

    for key in unDiccionario.keys():
        for num in unDiccionario[key]:
            listaResultado.append((key, num))
    return listaResultado
dic = Diccionario((5, 8), ([5,3,7], [15,3]))
print(dic)
print(combinacionesDe(dic))

{(8, [15, 3]), (5, [5, 3, 7])}
[(8, 15), (8, 3), (5, 5), (5, 3), (5, 7)]


### **Ejercicio 12**

Escribir una función que haga lo inverso del Ejercicio 9.

Por ejemplo:

Lista de entrada = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]

Diccionario de salida = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }




In [2]:
def factorComunClave(unaLista: list[tuple[int,int]]) -> dict:
    dictResultado = Diccionario()
    num = 0
    for tupla in unaLista:# Se puede en el for poner 2 variables para desenpaquetar
      if num != tupla[0]:
        num = tupla[0]
        dictResultado.insert(num, [tupla[1]])
      else:
        dictResultado[num].append(tupla[1])
    return dictResultado




print(factorComunClave([ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]))

{(8, [15, 3]), (5, [5, 3, 7])}


### **Ejercicio 13**

Escribir el TDA **MatrizDePixels**, que modele una matriz de pixels (imagen) de **N x M** usando el tipo array del paquete numpy, donde cada pixel tiene un color representado por un número entero entre **0 y 255**.

Hacer las operaciones del TDA para crear una MatrizDePixels (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixels de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixels de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** da un error




In [ ]:
import numpy as np

class MatrizDePixels2:
   def __init__(self, cantFilas: int, cantCols: int):
      self.__imagen = np.zeros((cantFilas, cantCols), int)

   def __repr__(self) -> str:
      return str(self.__imagen)

   def escribirPixel(self, posFila:int, posCol: int, valor:int) -> None:
        self.__imagen[posFila, posCol] = valor

   def leerPixel(self, posFila:int, posCol:int) -> int:
        return self.__imagen[posFila, posCol]

In [ ]:
import numpy as np

class MatrizDePixels:
  def __init__(self, cantFilas: int, cantCols: int)-> None:
      self.__imagen = np.zeros((cantFilas, cantCols), int)

  def __repr__(self) -> str:
      return str(self.__imagen)

  def escribirPixel(self, posFila:int, posCol: int, valor:int)->None:
      self.__imagen[posFila][posCol] = valor

  def leerPixel(self, posFila:int, posCol: int) -> int:
      return self.__imagen[posFila][posCol]


miImagen = MatrizDePixels(100 , 100) #Creo una imagen de 100 x 100
print(miImagen) #La vemos
miImagen.escribirPixel(0 , 0 , 255) #Cambio el primer elemento de 0 a 255
miImagen.escribirPixel(99 , 99 , 255) #Hago lo mismo con el último
print(miImagen)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[255   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 255]]


Ahora escribir el TDA **MatrizDePixelsDict**, que modele una matriz de pixels (imagen) de **N x M** usando un diccionario de **<(fila,columna) , pixel>**, donde cada pixel tiene un color representado por un número entero entre **0 y 255** y el par **(fila,columna)** indica la posición del pixel en la matriz.

Hacer las operaciones del TDA para crear una MatrizDePixelsDict (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixelsDict de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixelsDict de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** ahora si funciona

**Nota:** Si importan el paquete **sys** pueden usar la función **sys.getsizeof(variable)** que retorna el espacio que ocupa una variable en memoria.

In [ ]:
import numpy as np

class MatrizDePixelsDict: #Ahora hacemos nuestro nuevo TDA, basado en un diccionario
  def __init__(self, cantFilas:int, cantCols:int): #TOma cantidad e ilas y de columnas
    self.__xsize = cantFilas #Guardamos cantidad de filas
    self.__ysize = cantCols #Guardamos cantidad de columnas
    self.__imagen = Diccionario() #Instanciamos el diccionario. No guardamos nada porque asumimos que es todo 0

  def __repr__(self)->str: #El repr será entonces mi diccionario de pixels distintos de cero y las dimensiones de la matriz
    return f"{self.__imagen} ({self.__xsize}, {self.__ysize})"

  def escribirPixel(self, posFila:int, posCol:int, valor:int)->None: #Par escribir el pixel ponemos como clave la psoción y como value el valor correspondiente
    self.__imagen[(posFila,posCol)] = valor

  def leerPixel(self, posFila:int, posCol:int)->int: #Par aller el pixel instanciamos el valor como 0
    valor = 0 #Porque si es distinto de 0 lo tenemos en el diccioario, sino no
    if (posFila,posCol) in self.__imagen: #Si tenemos guardada esa posición en particular, decimos el valor, sino se saltea este if y asumimos que es 0
      valor = self.__imagen[(posFila,posCol)]
    return valor

imagen1 = MatrizDePixelsDict(10,10)
imagen1.escribirPixel(2,3,5)
imagen1.escribirPixel(4,1,10)
print(imagen1)

{((2, 3), 5), ((4, 1), 10)} (10, 10)


### **Ejercicio 14**

Implementar la suma matrices como operación en el TDA **MatrizDePixelsDict** implementado en el Ejercicio 13.

In [ ]:
class MatrizDePixelsDict2:
  def __init__(self, cantFilas: int, cantCols: int)-> None:
      self.__cantFilas = cantFilas
      self.__cantCols = cantCols
      self.__imagen = Diccionario()

  def __repr__(self) -> str:
      return str(self.__imagen)

  def escribirPixel(self, posFila:int, posCol: int, valor:int)->None:
      self.__imagen[(posFila, posCol)] = valor

  def leerPixel(self, posFila:int, posCol: int) -> int:
      dato = 0
      if [posFila, posCol] in self.__imagen:
          dato = self.__imagen[posFila, posCol]
      return dato

   def __add__(imagen1, imagen2):#resolver
      pass