# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 4: Recursividad** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con el concepto de recursividad en Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### Sergio: **sergio.gonzalez@unahur.edu.ar**

In [ ]:
#N y M positivos
#NxM = N + N*(M-1)   si M distinto de 1
#      N             si M igual 1
def producto(N:int, M:int)->int:
  salida = None
  if M == 1:
    salida = N
  else:
    salida = N + producto(N,M-1)
  return salida

In [ ]:
print(producto(2,2))

4


### **Ejercicio 1**

Implementar una función que calcule el factorial de un número de forma recursiva

In [1]:
def factorial(N:int) -> int:
  salida = None
  if N <= 0:
      salida = 1
  else:
      salida = N * factorial(N-1)
  return salida

print(factorial(3))

6


### **Ejercicio 2**

Una canilla de una casa pierde agua de forma que todos los días pierde 2 gotas más que el día anterior. Escribir una función recursiva que calcule cuantas gotas perderá la canilla el día N. El primer día solo perdía dos gotas.

De manera opcional, con un ciclo que llame N veces a la función recursiva,calcular la cantidad de gotas acumuladas en N días.

In [2]:
# dia     cantgotas   cant acum
#  1          2           2
#  2          4           6
#  3          6           12
#  4          8           20
#gotasPerdidas(diaN) = 2                             si diaN == 1
#                    = 2 + gotasPerdidas(diaN-1)     si diaN != 1

def gotasPerdidas(diaN:int)->int:
  resultado = None
  if diaN <= 0:
    resultado = 0
  else:
    resultado = diaN * 2 + gotasPerdidas(diaN - 1)
  return resultado

In [5]:
print(gotasPerdidas(3))

12


### **Ejercicio 3**

Implementar una función recursiva que calcule los números de la serie de Fibonacci. La función para generar la serie de Fibonacci es la siguiente (donde N es el índice del número en la serie):

<img src="https://blog.kakaocdn.net/dn/Fn13B/btretb0ZSLZ/qhgI2mFGD4cRCEVLN7PSKK/img.gif" width="300">

Luego escribir un programa que pida un número N (mayor o igual a 0) al usuario e imprima por pantalla los primeros N números de la serie de Fibonacci

Sobre la sucesion de Fibonacci: https://www.vix.com/es/btg/curiosidades/4461/que-es-la-sucesion-de-fibonacci




In [ ]:
def fibo(n:int)->int:
  numeroFibo = None
  if n == 0:
    numeroFibo = 0
  elif n == 1:
    numeroFibo = 1
  else:
    numeroFibo = fibo(n-1) + fibo(n-2)
  return numeroFibo

In [ ]:
print(fibo(42))

267914296


### **Ejercicio 4**

Escribir una función recursiva que calcule el número triangular de índice N. El número triangular de índice N es la suma de todos los números desde 1 hasta N.

Algunos ejemplos:

*T(1) = 1*

*T(2) = 3 = 1 + 2*

*T(3) = 6 = 1 + 2 + 3*

*T(4) = 10 = 1 + 2 + 3 + 4*

*T(5) = 15 = 1 + 2 + 3 + 4 + 5*

...

*T(N) = 1 + 2 + 3 + 4 + ... + N*

### **Ejercicio 5**

En las redes sociales se produce una continua interacción y cada vez que un usuario realiza una acción, la comunidad se modifica. Suponiendo que un *influencer* que usa ***Instagram*** cada vez que postea algo, aumenta su cantidad de seguidores según la siguiente regla:
- Durante los primeros 20 posteos, siempre suma una cantidad fija de 1000 (mil) seguidores en cada uno.
- A partir del posteo 21, la cantidad de seguidores duplica la cantidad previa de seguidores, mas  500 seguidores extra.

Implementar una función recursiva que permita saber cuantos seguidores tendra el *Instagramer* luego de una cantidad determinada de posteos.

In [ ]:
#seguidores(p) = 0                                si p == 0
#              = 1000 + seguidores(p-1)           si p <= 20
#              = 2 * seguidores(p-1) + 500        si p >= 21

#seguidores(p) = 1000 * p                         si 0 <= p <= 20
#              = 2 * seguidores(p-1) + 500        si p >= 21

def seguidores(posteo:int)->int:
  cantSeg = 0
  if posteo == 0:
    cantSeg = 0
  elif posteo <= 20:
    cantSeg = 1000 + seguidores(posteo-1)
  else:
    cantSeg = 2 * seguidores(posteo-1) + 500
  return cantSeg

def seguidoresBis(posteo:int)->int:
  cantSeg = 0
  if 0 <= posteo <= 20:
    cantSeg = 1000 * posteo
  else:
    cantSeg = 2 * seguidoresBis(posteo-1) + 500
  return cantSeg

In [ ]:
N = 22
print(seguidores(N))
print(seguidoresBis(N))

81500
81500


### **Ejercicio 6**

Un equipo de albañiles de una obra, tiene que planificar la colocación de pisos. Dicha tarea se realiza teniendo algunas consideraciones específicas, que tienen que ver con el corte de las baldosas, con el material de pegado y la cantidad de trabajadores que hay en cada momento. En el arranque, el día uno (1), los albañiles colocan siempre 100 baldosas.
Luego, la cantidad que se coloca cada día se organiza de esta manera:
- Los días pares se colocan el doble de baldosas del día anterior.
- Los días impares (salvo el primer día) se coloca una cantidad igual a la suma de las que se colocaron los 2 dias anteriores.

Implementar una función que permita saber la cantidad de baldosas que se colocan en total luego de transcurrida una determinada cantidad de días.

In [ ]:
def cantidadTotalBaldosas(dias:int, dia:int=1, anterior:int=100, previo:int=200)->int:
    if dia > dias:
        return 0
    if dia == 1:
        cantidad = 100
    elif dia % 2 == 0:
        cantidad = anterior * 2
    else:
        cantidad = anterior + previo
    return cantidad + cantidadTotalBaldosas(dias, dia + 1, cantidad, anterior)

dias = int(input("Introduce la cantidad de días: "))
totalBaldosas = cantidadTotalBaldosas(dias)
print(f"En {dias} días se colocaron un total de {totalBaldosas} baldosas.")

In [ ]:
def cantBaldosas(dia:int)->int:
  salida = None
  if dia == 1:
    salida=100
  elif dia > 1:
    if dia%2 == 0:
      salida = cantBaldosas(dia-1)*2
    else:
      salida = cantBaldosas(dia-2)+cantBaldosas(dia-1)
  return salida

print(cantBaldosas(500))

KeyboardInterrupt: 

In [ ]:
def cantBaldosasAcumuladas(dias:int)->int:
  baldosasTotales = 0
  for dia in range(1,dias+1):
    baldosasTotales += cantBaldosas(dia)
  return baldosasTotales

In [ ]:
#100, 200, 300 , 600, 900
#dia1,dia2,dia3,dia4,dia5

#cantTotal(dias) = cantTotal(dias-1) + cantBaldosas(dia)
#cantTotal(5) = cantTotal(4) + cantBaldosas(5)

def cantBaldosasAcumuladas(dias:int)->int:
  baldosasTotales = 0
  if dias == 1:
    baldosasTotales = cantBaldosas(dias) #100
  else:
    baldosasTotales = cantBaldosas(dias) + cantBaldosasAcumuladas(dias-1)
  return baldosasTotales


### **Ejercicio 7**

Luego de una lluvia muy grande se acumula gran cantidad de agua en un estanque, durante el primer día, el agua comienza a ponerse de color verde y un grupo de científicos decide medir cuantas algas encuentra dentro del tanque. La primer medición le da como resultado 12 algas. Luego deciden ir a realizar la medición todos los días para tratar de establecer un patrón de crecimiento y se encuentran que las algas crecen con la siguiente regla:
- Durante los siguientes 10 días (del dia 2 al 11) la cantidad de algas en el tanque es 15 más de las que había el día anterior.
- A partir del día 12, la cantidad de algas en el tanque es el triple de las que había el día previo más una cantidad fija de 100.

Escriba una función recursiva que calcule la cantidad de algas en el tanque en un día N.

Nota: Suponer que no mueren algas en el tanque.

### **Ejercicio 8**

Escribir una función recursiva que calcule la potencia N de un número M (M a la N), ambos números enteros positivos.   

In [ ]:
#M^N = M*M*M*.....*M (N veces)
#    = M * (M*M*....*M)
#    = M * M^(N-1)              N > 1
#    = M                        si N == 1

### **Ejercicio 9**

Problema del trigo en el tablero de ajedrez:

 <img src="https://i0.wp.com/matematicascercanas.com/wp-content/uploads/2015/03/leyenda_ajedrez.jpg?w=600&ssl=1" width="400">

Si se colocase sobre un tablero de ajedrez, un grano de trigo en el primer casillero, dos en el segundo, cuarto en el tercero y asi sucesivamente, doblando la cantidad de granos en cada casilla ¿Cuantos granos de trigo habría en el tablero en total al final? Resolver el problema con una función recursiva.

Leyenda del Trigo y el tablero de ajedrez y mas datos: https://matematicascercanas.com/2014/03/10/la-leyenda-del-tablero-de-ajedrez-y-los-granos-de-trigo/

In [ ]:
#Hacerlo con dos funciones
#1. Calcula recursivamente la cantidad de granos por casillero
#2. Calcula la suma total de granos en un tablero de N casilleros (iterativa o recursiva)

#Hacerlo con una funcion aprovechando la relacion exponencial
#cantGranos(n) = 2^(n-1)   (cuando el primer casillero es el numero 1)
#cantGranos(n) = 2^n   (cuando el primer casillero es el numero 0)
#1. Calcula la suma total de granos en un tablero de N casilleros (recursiva)

### **Ejercicio 10**

En un edificio alto, las cucarachas se van distribuyendo por pisos de esta forma:
- En el primer piso hay una cucaracha
- En los pisos pares el doble del número de piso (por ejemplo en el piso 8 hay 16 cucarachas)
- El resto de los pisos tienen la suma de las cucarachas de los dos pisos anteriores.

Escribir una función recursiva que calcule la cantidad de cucarachas en un edificio en función de la cantidad de pisos.

### **Ejercicio 11**

Escribir la función recursiva repetirPalabra, que recibe como parámetro una palabra (cadena de caracteres) y un número N. La función debe retornar una nueva cadena que contenga la palabra repetida N veces, por ejemplo:

*repetirPalabra("hola",3) -> "holaholahola"*

In [ ]:
#repetirPalabra("palabra", 3) = "palabrapalabrapalabra"
#                             = "palabra" + "palabrapalabra"
#                             = "palabra" + repetirPalabra("palabra", 2)
#repetirPalabra(str, N) = str + repetirPalabra(str, N-1)     si N > 1
#                       = str                                si N == 1

### **Ejercicio 12**

Juan y María empiezan a trabajar el mismo día en dos empresas distintas. Juan arregla un sueldo inicial de \$40000 con una actualización mensual del 2% y María un sueldo inicial de \$25000 con una actualización mensual del 5%. Calcular recursivamente los sueldos de Juan y de María luego de transcurridos una cantidad determinada de meses.

Luego, escribir una función que retorne cuantos meses tienen que pasar para que el sueldo de María supere al de Juan (Esta parte no hace falta que sea recursiva, pero pueden intentar hacerlo).

In [ ]:
#calcularSueldoJuan(Nmes)
#calcularSueldoMaria(Nmes)

#calcularSueldo(Nmes, ....) Falta parametrizar para que funcione para cualquier persona

## **Recursividad sobre vectores**

### **Ejercicio 13**

Escribir una función **recursiva** que reciba un vector como parámetro y retorne la suma de todos sus elementos.

### **Ejercicio 14**

Escribir una función **recursiva** que retorna *True* si un string es un palindromo y *False* en caso contrario.

Nota: Palíndromo es la forma elegante de "capicua"

### **Ejercicio 15**

Escribir una función que implemente de forma **recursiva** el algoritmo de **búsqueda binaria** sobre un vector.

https://es.khanacademy.org/computing/computer-science/algorithms/binary-search/a/binary-search

### **Ejercicio 16**
Implementar una función recursiva para encontrar el máximo elemento de un arreglo

In [ ]:
import numpy as np
def maximo(v:np.array(int))->int:
  valorMaximo = None
  if len(v) == 1:
    valorMaximo = v[0]
  else:
    valorMaximo = max(v[0], maximo(v[1:]))
  print(v, f"maximo={valorMaximo}")
  return valorMaximo

print(maximo(np.array([2,3,10,3])))

[3] maximo=3
[10  3] maximo=10
[ 3 10  3] maximo=10
[ 2  3 10  3] maximo=10
10


In [ ]:
import numpy as np
def maximo(v:np.array(int), posInicio:int=0)->int:
  valorMaximo = None
  if posInicio == len(v) - 1:
    valorMaximo = v[posInicio]
  else:
    valorMaximo = max(v[posInicio], maximo(v, posInicio+1))
  print(v, f"pos={posInicio}", f"maximo={valorMaximo}")
  return valorMaximo

print(maximo(np.array([2,3,10,3])))

[ 2  3 10  3] pos=3 maximo=3
[ 2  3 10  3] pos=2 maximo=10
[ 2  3 10  3] pos=1 maximo=10
[ 2  3 10  3] pos=0 maximo=10
10


### **Ejercicio 17**
Implementar una función recursiva para encontrar la posicion del máximo elemento de un arreglo