# ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png) **Trabajo Práctico 6: Diccionarios** ![alt text](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/50px-Python-logo-notext.svg.png)

En este trabajo práctico, vamos a trabajar con la estructura de datos **Diccionario** basado en el conjunto de Python. Recuerden crear una copia de este archivo en su ***Google Drive*** para tener permisos de edición.

### **florencia.dias@unahur.edu.ar** ###


Declaracion de conjuntos e inserción de elementos

In [ ]:
conj1 = set()
print(conj1)
conj1.add(1);conj1.add(10);conj1.add(2);conj1.add(4);
print(conj1)

set()
{1, 10, 2, 4}


Declaración y manejo de tuplas

In [2]:
tupla1 = (2,[1,2,3,3])
tupla1[1].append(4) # accede al segundo elemento de la tupla "[]"
print(tupla1)

(2, [1, 2, 3, 3, 4])


### **Ejercicio 1**

Implementar el TDA **Diccionario (Map)**, con las siguientes operaciones (Solo lo tienen que usar, ya esta implementado por nosotros, pero repasen el funcionamiento):
- Crear (**\_\_init__()**).
- **\_\_repr__()**: Para poder imprimir por consola.
- **insertar(clave, significado)**: Inserta el par **<clave , significado>**, si la clave ya existe no debe modificar el diccionario.
- **Asignación con "dicc[clave] = significado"**: Permite modificar significados de claves existentes y agregar nuevos pares. Esto se realiza implementado la función **\_\_setitem__()**.
- **get(clave)**: Recibe una clave y retorna su significado, si la clave no existe lanza una excepción.
- **Obtener con "dicc[clave]"**: Similar a **get**, pero con el operador **"[ ]"**. Esto se realiza implementando la función **\_\_getitem__()**.
- **len()**: Retorna la cantidad de pares **<clave , significado>** en el diccionario.
- **getKeys()**: Retorna lista con claves.
- **getValues()**: Retorna lista con significados.
- **Operador "in"**: Permite la búsqueda dentro del diccionario por las claves, es decir podemos hacer **"if clave in diccionario"**.
- **remove(clave)**: Elimina el par clave-significado que contiene la clave que recibe como parámetro
- **clone()**: Genera nuevo diccionario con el mismo contenido
- **clear()**: Vacia diccionario

Si quieren iterar el diccionario deben hacer (por ejemplo para imprimir todos los pares clave-significado en diferentes lineas):

    
    for clave in diccionario.keys():
        print(clave, diccionario.get(clave))

O el equivalente con el operador **"[ ]"**:


    for clave in diccionario.keys():
        print(clave, dicionario[clave])

Aunque tengamos el operador **"in"** este sirve solo para búsquedas y no para iterar en diccionario, entonces no se puede hacer:


    for clave in diccionario:








In [ ]:
print(hash("hola mundo!"))

7662369221931819884


In [6]:
import copy as cp

class Diccionario:
  #######TDA tupla clave-significado#########################
  class __TuplaDic:
    def __init__(self, key, value):
      self.__data = (key,value)

    def __repr__(self):
      return str(self.__data)

    def __eq__(self, key): # sobrecargar el numerador "==", compara las key y no los value.
      return self.__data[0] == key

    def __hash__(self): # metodo necesario para asociar claves con valores
      return hash(self.__data[0])

    def getKey(self): # devuelve la key
      return self.__data[0]

    def getValue(self): # devuelve el valor
      return self.__data[1]
  ############################################################

  ###Constructor recibe dos listas de claves y significados en orden
  def __init__(self, keys = None, values = None):
    self.__diccionario = set()
    if keys != None:
      if len(keys) == len(values):
        for i in range(len(keys)):
          self[keys[i]] = values[i]
      else:
        raise Exception("Las listas de pares clave-significado deben tener la misma cantidad")

  def __repr__(self):
    return str(self.__diccionario)

  ###Asignacion usando [], se recibe clave entre corchetes / Permite reemplazar aunque exista la clave
  def __setitem__(self, key = None, value = None):
    if key != None:
      if key in self:
        self.__diccionario.remove(key)
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###No inserta si existe la clave, es decir, si la clave existe en el dicc no modifica el valor
  def insert(self, key = None, value = None):
    if key != None:
      self.__diccionario.add(Diccionario.__TuplaDic(key,value))

  ###Elimina si existe la clave, es decir, si la clave existe en el dicc elimina el par clave-valor
  ###Sino existe la clave, no hace nada
  def remove(self, key):
    if key in self:
        valor = self[key]
        self.__diccionario.remove(key)
        return valor

  ###Vacia dicc
  def clear(self):
    self.__diccionario = set()

  ###Clonar dicc
  def clone(self):
    return cp.deepcopy(self)

  ###Acceso a valores usando [], se recibe clave entre corchetes
  def __getitem__(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna valor de la clave que se recibe por parametro
  def get(self, key):
    value = None
    flag = False
    for tuplaDic in self.__diccionario:
      if tuplaDic.getKey() == key:
        value = tuplaDic.getValue()
        flag = True
    if flag:
      return value
    else:
      raise Exception("No existe la clave %s en el diccionario" % (key))

  ###Retorna lista con claves
  def keys(self):
    return [x.getKey() for x in self.__diccionario]

  ###Retorna lista con valores
  def values(self):
    return [x.getValue() for x in self.__diccionario]

  ###Operador "in"
  def __contains__(self, key):
    flag = False
    for tupla in self.__diccionario:
        if tupla.getKey() == key:
            flag = True
            break
    return flag

  ###Tamaño de diccionario
  def len(self):
    return len(self.__diccionario)

In [ ]:
dic1 = Diccionario()
dic1.insert(1,"uno")
dic1.insert(2,[2,3,4,5])
print(dic1)
var = 1
print(dic1[var]) # imprime el primer valor de la tupla correspondiente a key = 1
dic1[2] = "hola" # cambia el valor
print(dic1)
dic1.remove(1)
print(dic1)

{(1, 'uno'), (2, [2, 3, 4, 5])}
uno
{(1, 'uno'), (2, 'hola')}
{(2, 'hola')}


In [ ]:
dic2 = Diccionario((1,2,3,4),("casa", "perro", "gato", "auto"))
for clave in dic2.keys():
  print(clave, dic2[clave])

print(40 in dic2)


1 casa
2 perro
3 gato
4 auto
False


In [ ]:
notas = Diccionario(("juan","pedro","maria"),([],[],[]))
print(notas)
notas["juan"].append(4)
print(notas)
print(notas.len())

{('pedro', []), ('maria', []), ('juan', [])}
{('pedro', []), ('maria', []), ('juan', [4])}
3


### A partir del **Ejercicio 2** vamos a trabajar **fuera del TDA Diccionario** usando la interface que creamos en el **Ejercicio 1**. Es decir,se pueden usar solo las operaciones de la interface, no se puede acceder a los componentes internos del TDA. Si necesitan estructuras auxiliares, pueden usar cualquiera de las estructuras que vimos hasta ahora: Arreglos, Listas, Pilas, Colas, Diccionarios.

In [ ]:
dic = Diccionario() #diccionario vacio
dic = Diccionario(("casa",3,4,5),([2,3,1],[4,1,4,2,5],[2,3,1],[4,1,2,6,3,2]))
print(dic)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [4, 1, 2, 6, 3, 2]), ('casa', [2, 3, 1])}


In [ ]:
#insercion
dic.insert(5,[0,6,5,3,1])
dic[5] = [0,6,5,3,1]
dic[10] = [4,1,34,43,2,45,4]
print(dic)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}


In [ ]:
#lectura
print(dic.get(3))
print(dic[3])

[4, 1, 4, 2, 5]
[4, 1, 4, 2, 5]


In [ ]:
print(dic)
var = dic.remove(4)
print(dic)
print(var)

{(3, [4, 1, 4, 2, 5]), (4, [2, 3, 1]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}
{(3, [4, 1, 4, 2, 5]), (5, [0, 6, 5, 3, 1]), (10, [4, 1, 34, 43, 2, 45, 4]), ('casa', [2, 3, 1])}
[2, 3, 1]


In [ ]:
for clave in dic.keys():
  print(clave)
  print(dic[clave])

3
[4, 1, 4, 2, 5]
5
[0, 6, 5, 3, 1]
10
[4, 1, 34, 43, 2, 45, 4]
casa
[2, 3, 1]


In [ ]:
print(40 in dic)

False


### **Ejercicio 2**

Escribir un programa que declare un Diccionario de **<entero , entero>** (clave entero y significado entero) y le agrege 4 pares. Luego debe mostrar el diccionario por pantalla y su tamaño.

Finalmente, redefinir 2 significados y volver a imprimir.

In [ ]:
dic = Diccionario() #Declaramos un diccionario. No es necesario definir de entrada los tipos de datos de las keys o de los values
dic.insert(1,200) #Agregamos el primer par
dic.insert(2,10) #EL segundo par
dic[23] = 456 #El tercer par, la idea es mostar una forma distinta de hacerlo. Recordar que insert no modifica el valor si la clave existe, en cambio esta versión sí lo hace
dic[123] = 745435 #Agregamos el cuarto par

print(dic) #Verificamos cómo quedó nuestro diccionario

dic[23] = 1 #Reemplazamos los valores para la key = 23
dic[123] = 4 #Reemplazamos los valores para la key = 123

print(dic) #Evaluamos nuevamente nuestro diccionario

{(1, 200), (2, 10), (123, 745435), (23, 456)}
{(1, 200), (2, 10), (123, 4), (23, 1)}


In [ ]:
dic.insert(23 , 8888888) #Notar que si hacemos insert sobre una clave que ya tenemos definida NO PASA NADA
print(dic)

{(1, 200), (2, 10), (123, 4), (23, 1)}


### **Ejercicio 3**

Escribir un diccionario con sinónimos. Luego intentar insertar dos pares **<clave , significado>** con claves **repetidas** con la operacion **insert** y ver que sucede.

In [6]:
palabras = ['casa' , 'perro' , 'computadora'] #Creamos una lista de palabras
sinonimos = ['hogar' , 'can' , 'ordenador'] #Una lista de sinónimos

dicc_sinonimos = Diccionario(keys = palabras , values = sinonimos) #Instanciamos nuestro diccionario con las palabras y los sinonimos
print(dicc_sinonimos) #Vemos cómo está nuestro diccionario

print('-'*50) #Linea horizontal

dicc_sinonimos['casa'] = 'casita' #Cambiamos el valor sin usar insert, donde hay una key conocida
dicc_sinonimos.insert('computadora' , 'PC') #Cambiamos el valor usando insert, donde hay una key conocida
print(dicc_sinonimos) #Vemos cómo quedó nuestro diccionario

{('perro', 'can'), ('casa', 'hogar'), ('computadora', 'ordenador')}
--------------------------------------------------
{('perro', 'can'), ('casa', 'casita'), ('computadora', 'ordenador')}


In [ ]:
#Tamién se podía hacer así si uno no quería usar las listas #Pero es mucho más largo
dicc_sinonimos = Diccionario()
dicc_sinonimos.insert('casa' , 'hogar')
dicc_sinonimos.insert('perro' , 'can')
dicc_sinonimos.insert('computadora' , 'ordenador')
print(dicc_sinonimos)

{('perro', 'can'), ('casa', 'hogar'), ('computadora', 'ordenador')}


### **Ejercicio 4**

Escribir una función que dado una lista de enteros me devuelve otra(no necesariamente en el mismo orden) sin los numeros repetidos.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Lista de salida = [1 , 3 , 2, 4]

In [ ]:
def eliminarRepetidos(unaLista:list)->list: #Defino mi función que toma una lista y devuelve una lista sin repetidos
  dicc_aux = Diccionario(unaLista , unaLista) #Declaro una estructura auxiliar. Un diccionario que toma como claves y como valores los números
  sin_repetidos = dicc_aux.keys() #Como las keys no se pueden repetir, por construcción el diccionario me eliminará los valores repetidos. Me interesan solo las keys (porque los values son lo mismo)

  return sin_repetidos #Retorno la lista de keys

lista_de_entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]
lista_de_salida = eliminarRepetidos(lista_de_entrada)

print(lista_de_salida)

[1, 2, 3, 4]


### **Ejercicio 5**

Rehacer le ejercicio 4 pero retornando un diccionario en lugar de una lista.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

Diccionario de salida = { (1 , None) , (3 , None) , (4 , None) , (2 , None) }

In [ ]:
def listToDict(numeros:list)->Diccionario: #Defino mi función que toma una lista de números y retorna un diccionario
  salida = Diccionario() #Instancio un diccionario vacío para crear mi diccionario de salida
  for numero in numeros: #Para cada número en mi lista de números
    salida.insert(numero) #A la salida le inserto un número. Pero ojo! Insert recibe una tupla key-value. Si solo le paso un parámtero le estoy pasando solo la key. Si le paso una key repetida esto no hará nada, pero al no tener value lo asignará automáticamente como None
  return salida #Retornamos el diccionario de salida

listaEntrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

print(listToDict(listaEntrada))

{(1, None), (2, None), (3, None), (4, None)}


In [ ]:
#Otra forma de verlo
def listToDict2(numeros:list)->Diccionario: #Defino mi función igual que antes, tomo una lista de números y devuelvo un diccionario
  salida = Diccionario() #Instancio mi diccionario vacío para guardar los resultados
  for numero in numeros: #Para cada número en mi lista de números
    salida[numero] = None #En salida guardo la key número y le asigno el value None. Esto va a pisar los repetidos, pero como el value es el mismo no me importa
  return salida #Retorno la salida

listaEntrada = [1 , 3 , 4 , 1 , 2 , 4 , 3 , 2]

print(listToDict2(listaEntrada))

{(1, None), (2, None), (3, None), (4, None)}


In [ ]:
print(listToDict([1 , 3 , "4" , "casa" , 2 , 4 , 3 , 2])) #Ojo con los tipos de datos!

{(1, None), (2, None), (3, None), (4, None), ('casa', None), ('4', None)}


In [ ]:
print(listToDict2([1 , 3 , "4" , "casa" , 2 , 4 , 3 , 2]))

{(1, None), (2, None), (3, None), (4, None), ('casa', None), ('4', None)}


### **Ejercicio 6**

Escribir una función que recibe una lista de números como parámetro y devuelve un diccionario con los números de la lista como claves y la cantidad de apariciones de cada uno como su significado.

Por ejemplo:

Lista de entrada = [1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 2) , (2 , 3) , (5 , 1) }

In [ ]:
#declaro diccionario de salida
#itero la lista de entrada
#  si el elemento actual NO esta como clave en el dicionario de salida -> insertar el par (elemento,1)
#  si el elemento actual SI esta como clave en el dicionario de salida -> actualizo su valor sumando uno al valor actual
#retorno diccionario de salida

def contarOcurrencias(listaNumeros:list)->Diccionario: #Defino mi función "contarOcurrencias" que toma una lista de números y retorna un diccionario
  dicSalida = Diccionario() #Instancio mi diccionario vacío, donde voy a construir el resultado
  for numero in listaNumeros: #Para cada número en mi lista de números
    if numero not in dicSalida: #Si el número NO ESTÁ en el diccionario de salida, es decir, si todavía no tengo una key con ese valor:
      dicSalida[numero] = 1 #Es la primer ocurrencia, entonces el value para esa key va a ser 1
      #dicSalida.insert(numero,1) #Si quisiéramos lo podríamos escribir así también
    else: #Sino, es decir, si el número YA ESTÁ como valor dentro de las keys:
      dicSalida[numero] += 1 #A ese valor que ya existe le sumamos 1
  return dicSalida #Una vez terminado el for, es decir, recorridos todos los números en mi lista de números, retornamos el diccionario

print(contarOcurrencias([1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]))

{(1, 3), (2, 3), (3, 2), (4, 2), (5, 1)}


In [ ]:
#Otra forma de verlo
def contarOcurrencias2(listaNumeros:list)->Diccionario: #Definimos de la misma forma que antes
  dicSalida = Diccionario() #Instancio mi diccionario vacío
  for numero in listaNumeros: #Para cada número en mi lista de números
    dicSalida.insert(numero,0) #Insertamos el valor del número y lo inicializamos como 0. El tema acá es que si la key ya existe, insert no lo reemplaza, entonces solo va a iniciarlo con los valores 0, sino no hace nada
    dicSalida[numero] += 1 #Luego le sumamos 1. En caso que sea la primer interación queda en 1, luego como ya existe, insert no hace nada y pasa directamente a sumar 1 al contador. Así nos ahorramos de hacer las estructuras condicionales
  return dicSalida #Finalizado el for, retornamos el diccionario de salida

print(contarOcurrencias2([1 , 3 , 4 , 2 , 1 , 3 , 1 , 4 , 2 , 5 , 2]))

{(1, 3), (2, 3), (3, 2), (4, 2), (5, 1)}


### **Ejercicio 7**

Escribir una función que recibe dos diccionarios y devuelve otro con la mezcla de los dos, para las claves repetidas, se queda con los significados de primer diccionario.

Por ejemplo:

Diccionario de entrada 1 = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) }

Diccionario de entrada 2 = { (10 , 3) , (3 , 5) , (2 , 30) , (8 , 1) , (9 , 3) }

Diccionario de salida = { (1 , 3) , (3 , 2) , (4 , 4) , (2 , 3) , (5 , 1) , (10 , 3) , (8 , 1) , (9 , 3) }

In [8]:
def mezcla_diccionarios(primerDiccionario:Diccionario , segundoDiccionario:Diccionario)->Diccionario: #Defino una función que toma dos diccionarios y devuelve un tercer dicccionario
  diccionario_final = primerDiccionario.clone() #Instancio mi diccionario de salida como clon del primer diccionario. Esto lo hago porque me piden que en caso de que se repita alguna key, conserve el valor del primer diccionario. Clonando me aseguro que pase esto por la cosntrucción propia del diccionario
  for key in segundoDiccionario.keys(): #Para cada key entre las keys de mi segundo diccionario:
    diccionario_final.insert(key , segundoDiccionario[key]) #Voy a insertar en mi diccionario final (clon del primer diccionario) la key y el valor correspondiente. En caso que esté repetida, no hace naad

  return diccionario_final #Una vez recorridas todas las keys del segundo diccionario, retornamos el diccionario final

diccionario_entrada1 = Diccionario([1 , 3 , 4 , 2 , 5] , [3 , 2 , 4 , 3 , 1])
diccionario_entrada2 = Diccionario([10 , 3 , 2 , 8 , 9] , [3 , 5 , 30 , 1 , 3])

diccionario_salida = mezcla_diccionarios(diccionario_entrada1 , diccionario_entrada2)

print(diccionario_salida)

{(1, 3), (2, 3), (3, 2), (4, 4), (5, 1), (8, 1), (9, 3), (10, 3)}


### **Ejercicio 8**

Escribir una función que modele el problema de administrar las materias que cursa un alumno.
Es decir que reciba un diccionario, un alumno y una materia y agregue esa materia a las materias que cursa.

**Nota: La lista de materias de cada alumno no debe tener materias repetidas.**

Por ejemplo:

Diccionario = { ( "Alumno1" , ["Materia1" , "Materia2"] )   ,   ( "Alumno2", [ "Materia2" , "Materia3" , "Materia4" ] ) }


In [ ]:
def agregaMaterias(diccionarioMaterias:Diccionario , alumno:str , materia:str)->Diccionario: #Defino una función que toma un diccionario de alumnos y materias, un alumno y una materia:
  if alumno in diccionarioMaterias.keys(): #Si mi alumno ya aparece en mi diccionario:
    if materia not in diccionarioMaterias[alumno]: #Y además esa materia NO ESTÁ dentro de las materias que tiene ese alumno (donde alumno es la key y el value es un array de materias)
      diccionarioMaterias[alumno].append(materia) #Appendeo la materia a las materias que cursa el alumno (modifico el value)
    else: #Sino, es decir, si la materia ya se encuentra dentro de las materias que tiene asignadas el alumno:
      raise Exception(f'{alumno} ya está asignado a la materia {materia}') #Lanzo una excepción, el alumno ya tiene esa materia asignada
  else: #Sino, es decir, que el alumno NO aparece entre los que ya están en el diccionario
    diccionarioMaterias.insert(alumno , [materia]) #Agrego al alumno y a su correspondiente materia como un nuevo par key - value:

  return diccionarioMaterias #Retornamos el diccionario de entrada, modificado

diccionarioMaterias = Diccionario(['Alumno1' , 'Alumno2'] , [['Materia1' , 'Materia2'] , ['Materia2' , 'Materia3' , 'Materia4']])
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'ALUMNX3' , 'MATERIA 5')
print(diccionarioMaterias)

agregaMaterias(diccionarioMaterias , 'Alumno1' , 'Materia3')
print(diccionarioMaterias)

{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('Alumno1', ['Materia1', 'Materia2'])}
{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('Alumno1', ['Materia1', 'Materia2']), ('ALUMNX3', ['MATERIA 5'])}
{('Alumno2', ['Materia2', 'Materia3', 'Materia4']), ('Alumno1', ['Materia1', 'Materia2', 'Materia3']), ('ALUMNX3', ['MATERIA 5'])}


### **Ejercicio 9**

Escribir una función listaToDic que recibe una lista con chirimbolos y devuelve un diccionario con cada chirimbolo como clave y como significado una matriz de nxn donde n es la cantidad de veces que aparece el chirimbolo en la lista. La matriz se debe llenar con el chirimbolo de la clave.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares. Si es necesario definir funciones auxiliares.
Ejemplo:

```
lista = [‘*’, ‘#’, ‘/’, ‘*’, ‘#’, ‘/’, ‘*’, ‘$’]
listaToDic(lista) –> Diccionario
Entonces, listaToDic(lista) =>
{(‘*’,  [[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’],[‘*’,‘*’,‘*’]]) , (‘$’ , [[‘$’]]), (‘/’ , [[‘/’,‘/’],[‘/’,‘/’]]) , (‘#’ , [[‘#’,‘#’],[‘#’,‘#’]])}
```

Ayuda: Se recomienda generar primero la matriz con ceros y luego reemplazarlos o bien utilizar la funcion np.full(...).

In [ ]:
import numpy as np
#l = ['#','!','#',')']
#Iteramos la lista de entrada
#guardar la cantidad de apariciones como valor del elemento como clave de un diccionario
#iterarar el diccionario por las claves y cambiar el significado por la matriz


#Inicio reciclando la función contar ocurrencias. La única diferencia es que cambié la palabara "número" por "elemento" para que se adecúe al dominio del problema, pero la lógica es exactamente la misma
def contarOcurrencias(listaElementos:list)->Diccionario: #Defino mi función "contarOcurrencias" que toma una lista de elementos y retorna un diccionario
  dicSalida = Diccionario() #Instancio mi diccionario vacío, donde voy a construir el resultado
  for elemento in listaElementos: #Para cada elemento en mi lista de elementos
    if elemento not in dicSalida: #Si el elemento NO ESTÁ en el diccionario de salida, es decir, si todavía no tengo una key con ese valor:
      dicSalida[elemento] = 1 #Es la primer ocurrencia, entonces el value para esa key va a ser 1
    else: #Sino, es decir, si el número YA ESTÁ como valor dentro de las keys:
      dicSalida[elemento] += 1 #A ese valor que ya existe le sumamos 1
  return dicSalida #Una vez terminado el for, es decir, recorridos todos los números en mi lista de números, retornamos el diccionario

def listaToDic(lista:list): #Defino mi función lista to dic que toma una lista
  resultado = contarOcurrencias(lista) #Instancio mi diccionario resultado como el producto de la función contarOcurrencias
  for key in resultado.keys(): #Para cada key en mis keys de resultados (los chirimbolos sin repetirse)
    nApariciones = resultado[key] #El número de apariciones será el value que tengo asociado a ese key, por construcción de ContarOcurrencias
    resultado[key] = np.full((nApariciones , nApariciones) , key) #ENtonces reemplazo el value asociado a la key que estoy viendo por una matriz llena del chirimbolo que tomo por key

  return resultado #Retornamos el resultado

In [ ]:
chirimbolos = ['*', '#', '/', '*', '#', '/', '*', '$']
chirimbolos_to_dic = listaToDic(chirimbolos)
print(chirimbolos_to_dic)

{('#', array([['#', '#'],
       ['#', '#']], dtype='<U1')), ('/', array([['/', '/'],
       ['/', '/']], dtype='<U1')), ('$', array([['$']], dtype='<U1')), ('*', array([['*', '*', '*'],
       ['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1'))}


### **Ejercicio 10**

Escribir la función promedios que recibe una lista de materias (strings) y una lista de notas (enteros) del mismo tamaño. Retorna un diccionario que posee como clave cada materia y como significado su nota promedio.
Se debe resolver usando las operaciones del TDA diccionario que vimos en clase, sin violar el encapsulamiento ni utilizando estructuras auxiliares.
Por ejemplo:


listaMaterias = [“Intro Prog”, **“Objetos”**, “Estructura de Datos”, “Intro Prog”, ”Inglés”, **“Objetos”**, “Estructura de Datos”]

listaNotas = [4, **4**, 4, 6, 7, **6**, 6]

dic  = promedios(listaMaterias , listaNotas)

Entonces, dic = { (“Intro Prog”, 5) , (“Estructura de Datos”,  5) , (”Inglés”, 7) , ( “Objetos”, 5) }

In [ ]:
def calculaPromedios(listaMaterias:list , listaNotas:list)->Diccionario: #Nuestra función toma dos listas (materias y notas) y devuelve un diccionario de promedios
  resultado = Diccionario() #Instanciamos nuestro diccionario resultado vacío
  for i in range(len(listaMaterias)): #Como voy a recorrer dos listas a la vez (materias y notas) me conviene iterar el índice más que los elementos, entonces, para cada índice en mi rango de tamaño de lista de materias:
    if listaMaterias[i] not in resultado.keys(): #Si la materia en cuestión NO ESTÁ en las keys ya definidas en mi diccionariok de resultado:
      resultado[listaMaterias[i]] = [1 , [listaNotas[i]]] #Creo la key con la materia en cuestión, su valor será una lista de dos componenetes: en la primer componente guardaré la cantidad de apariciones que vaya teniendo la materia, en la segunda las notas correspondientes
    else: #SIno, es decir, si la materia ya aparece dentro de mis lista de keys definidas:
      resultado[listaMaterias[i]][0] += 1 #En la primer componente de value, referida a la key en cuestión, sumo 1 (agrego una ocurrencia)
      resultado[listaMaterias[i]][1].append(listaNotas[i]) #En la segunda componente agrego (appendeo) la nota correspondiente
  #LLegado este punto recorrimos ambas listas, completamos nuestro dicc resultado PERO no tenemos los promedios, así que ahora vamos a iterar sobre las keys calculando el promedio
  for key in resultado.keys(): #Para cada key (materia) en mis keys:
    n = resultado[key][0] # N será el número de apariciones, primera componente del value corersponeidnte a dicha key
    sum = sumaElementos(resultado[key][1]) # sum será la sumatoria de todas las notas, que están guardadas dentro de un array.
    #Puede ser confuso pero la estructura de resultados hasta este punto es algo del estilo
    # MATERIA X: [ CUANTAS VECES APARECIÓ , ARRAY DE NOTAS] |||| MATERIA X: [N , [nota1 , nota2 , nota3 , ... notaN]]
    # Lo que queremos hacer es que para materia X cambiar ese array de dos elementos en un promedio, donde quede:
    # MATERIA X: PROMEDIO MATERIA X, que es lo mismo que decir |||| MATERIA X: SUM(NOTAS)/N

    resultado[key] = sum/n #Calculamos el promedio para la key correspondiente y pisamos los valores que teníamos temporales

  return resultado #Retornamos el resultado

def sumaElementos(unaLista:list)->int: #Defino mi función auxiliar suma elementos:
  resultado = 0 #Inicializo el resultado de la suma como 0
  for elemento in unaLista: #Para cada elemento en la lista
    resultado += elemento #El resultado será sumar cada nuevo elemento

  return resultado #Retorno el resultado

listaMaterias = ["Intro Prog", "Objetos", "Estructura de Datos", "Intro Prog", "Inglés", "Objetos", "Estructura de Datos"]
listaNotas = [4, 4, 4, 6, 7, 6, 6]

calculaPromedios(listaMaterias , listaNotas)

{('Inglés', 7.0), ('Estructura de Datos', 5.0), ('Objetos', 5.0), ('Intro Prog', 5.0)}

### **Ejercicio 11**

Tenemos un diccionario del tipo **<Entero , Lista de enteros>** (clave número entero, significado lista de enteros) que dado un numero **X**, guarda las posibles combinaciones de ese número con otros.

Escribir una función que recibe un diccionario de este tipo y devuelve una lista con los posibles pares de números (en formato de tupla).

Por ejemplo:

Diccionario de entrada = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }

Lista de salida = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]



In [ ]:
def distribucionClaves(dict1:Diccionario)->list[tuple[int,int]]: #Defino mu función distribución de claves que toma un diccionario y retorna una lista de tuplas de dos componentes enteros
  salida = [] #Instancio la salida, una lista vacía
  for clave in dict1.keys(): #Para cada key en mis keys:
    values = dict1[clave] #Los valores son los que están guardados en mis values:
    #Recorriendo lista por posiciones
    for pos in range(len(values)): #Para cada posición en mi rango de valores:
      salida.append((clave,values[pos])) #En la lista de salida voy a appendear o agregar a clave que estoy trabajando en tupla () con los valores correspondientes del arreglo
    #Recorriendo lista por valores
    #for num in dict1[clave]:
    #  salida.append((clave,num))
  return salida #retorno la salida

dic = Diccionario((5, 8), ([5,3,7], [15,3]))
print(dic)
print(distribucionClaves(dic))

{(8, [15, 3]), (5, [5, 3, 7])}
[(8, 15), (8, 3), (5, 5), (5, 3), (5, 7)]


### **Ejercicio 12**

Escribir una función que haga lo inverso del Ejercicio 9.

Por ejemplo:

Lista de entrada = [ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]

Diccionario de salida = { (5 , [5 , 3 , 7 ] )  ,  ( 8, [ 15 , 3 ] ) }




In [ ]:
def factorComunClave(listaTuplas:list[tuple[int,int]])->Diccionario: #Defino una función que toma lista de tuplas de enteros y retorna un diccionario
  salida = Diccionario() #Mi salida será un diccionario     #{(5, [5,3,7]), (8, [15,3])}
  for tupla in listaTuplas: #Para cada tupla en mi lista de tuplas
    pos0 = tupla[0] #La posición 0 es el número que voy a usar de key, o el agrupador si queremos pensarlo así (es el factor común)
    pos1 = tupla[1] #La posición 1 es el número que será agrupado en la lista
    if pos0 not in salida: #Si en salida aún no guardé ese núnmero defactor común, es decir, pos 0 no está en salida:
      salida[pos0] = [pos1] # Defino la key pos0 que no estaba y pos1 como único elemento dentro de una lista
    else: #Sino, es decir, que ya existe un key con el nombre pos 0
      salida[pos0].append(pos1) #Simplemente tengo que appendear pos1 en mi lista de números
  return salida #Retorno la salida

print(factorComunClave([ (5 , 5) ,(5 , 3) , (5 , 7) , (8 , 15) , (8 , 3) ]))

{(8, [15, 3]), (5, [5, 3, 7])}


### **Ejercicio 13**

Escribir el TDA **MatrizDePixels**, que modele una matriz de pixels (imagen) de **N x M** usando el tipo array del paquete numpy, donde cada pixel tiene un color representado por un número entero entre **0 y 255**.

Hacer las operaciones del TDA para crear una MatrizDePixels (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixels de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixels de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** da un error




In [4]:
import numpy as np

class MatrizDePixels: #Defino mi TDA Matriz de pixels
  def __init__(self, cantFilas:int, cantCols:int): #El constructor toma cantidad de filas y cantidad de columnas
    self.__imagen = np.zeros((cantFilas, cantCols), int) #La imagen será una matriz de filas x columnas y números enteros

  def __repr__(self)->str: #Defino el rpr
    return str(self.__imagen) #Es ver la matriz

  def escribirPixel(self, posFila:int, posCol:int, valor:int)->None: #Defino escribir pixel, que para un dado elemento de matriz marcamos el valor que nos indican oor parámetro
    self.__imagen[posFila,posCol] = valor #Asignamos en dicha posición el valor dado

  def leerPixel(self, posFila:int, posCol:int)->int: #Leer pixel recibe una posición en la matriz
    return self.__imagen[posFila,posCol] #Retorna el elemento en cuestión

miImagen = MatrizDePixels(100 , 100) #Creo una imagen de 100 x 100
print(miImagen) #La vemos
miImagen.escribirPixel(0 , 0 , 255) #Cambio el primer elemento de 0 a 255
miImagen.escribirPixel(99 , 99 , 255) #Hago lo mismo con el último
print(miImagen)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[255   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 255]]


In [ ]:
miImagen = MatrizDePixels(100000 , 50000) #Armo una imagen gigante
print(miImagen) #La veo
miImagen.escribirPixel(0 , 0 , 255) #Sxribo los pixels
miImagen.escribirPixel(99 , 99 , 255)
print(miImagen) #La veo

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[255   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [ ]:
type(miImagen.leerPixel(0,0)) #Vemos qué tipo de int usa

numpy.int64

In [ ]:
100000*50000*8 #Calculo cuántos bytes son en total

40000000000

Ahora escribir el TDA **MatrizDePixelsDict**, que modele una matriz de pixels (imagen) de **N x M** usando un diccionario de **<(fila,columna) , pixel>**, donde cada pixel tiene un color representado por un número entero entre **0 y 255** y el par **(fila,columna)** indica la posición del pixel en la matriz.

Hacer las operaciones del TDA para crear una MatrizDePixelsDict (por defecto llena de ceros), leer y escribir pixels.

Luego pruebenla con estos ejemplos:

**a)** Crear una MatrizDePixelsDict de **100 x 100** y agregarle valores a dos pixels.

**b)** Crear una MatrizDePixelsDict de **100000 x 50000** y agregarle valores a dos pixels.

Explicar porque el inciso **b** ahora si funciona

**Nota:** Si importan el paquete **sys** pueden usar la función **sys.getsizeof(variable)** que retorna el espacio que ocupa una variable en memoria.

In [9]:
import numpy as np

class MatrizDePixelsDict: #Ahora hacemos nuestro nuevo TDA, basado en un diccionario
  def __init__(self, cantFilas:int, cantCols:int): #TOma cantidad e ilas y de columnas
    self.__xsize = cantFilas #Guardamos cantidad de filas
    self.__ysize = cantCols #Guardamos cantidad de columnas
    self.__imagen = Diccionario() #Instanciamos el diccionario. No guardamos nada porque asumimos que es todo 0

  def __repr__(self)->str: #El repr será entonces mi diccionario de pixels distintos de cero y las dimensiones de la matriz
    return f"{self.__imagen} ({self.__xsize}, {self.__ysize})"

  def escribirPixel(self, posFila:int, posCol:int, valor:int)->None: #Par escribir el pixel ponemos como clave la psoción y como value el valor correspondiente
    self.__imagen[(posFila,posCol)] = valor

  def leerPixel(self, posFila:int, posCol:int)->int: #Par aller el pixel instanciamos el valor como 0
    valor = 0 #Porque si es distinto de 0 lo tenemos en el diccioario, sino no
    if (posFila,posCol) in self.__imagen: #Si tenemos guardada esa posición en particular, decimos el valor, sino se saltea este if y asumimos que es 0
      valor = self.__imagen[(posFila,posCol)]
    return valor

imagen1 = MatrizDePixelsDict(100,100)
imagen1.escribirPixel(2,3,5)
imagen1.escribirPixel(4,1,10)
print(imagen1)

{((2, 3), 5), ((4, 1), 10)} (100, 100)


### **Ejercicio 14**

Implementar la suma matrices como operación en el TDA **MatrizDePixelsDict** implementado en el Ejercicio 11.

In [10]:
#suma de matrices (valido para matrices de iguales dimensiones)
#     | 2  0 |        | 4  0 |
#M1 = | 0  7 |   M2 = | 1  2 |

#M1 + M2 = | 6  0 |
#          | 1  9 |
#dic1 = {((2,3),5) , ((4,1),10)}
#dic2 = {((4,1),2) , ((5,5),20)}
class MatrizDePixelsDict(MatrizDePixelsDict): #Así heredamos los métodos y extendemos nuestro TDA
  def __add__(imagen1, imagen2): #Add le indica a python como comportarse con el símbolo +
    imagenSuma = MatrizDePixelsDict(imagen1.__xsize, imagen1.__ysize) #Imagen suma será entonces un nuevo diccionario con los valores de alguna de las imagenes
    for clave in imagen1.__imagen.keys(): #para cada key en mis keys de imagen 1
      if clave in imagen2.__imagen: #Si la key se repite en la otra imagen:
        imagenSuma.escribirPixel(clave[0], clave[1], imagen1.__imagen[clave]+imagen2.__imagen[clave]) #El valor resultante será la suma de ambos
      else: #Sino
        imagenSuma.escribirPixel(clave[0], clave[1], imagen1.__imagen[clave]) #Agrego el valor del 1
    for clave in imagen2.__imagen.keys(): #Para cada key en las keys de la imagen 2
      if clave not in imagen1.__imagen: #Si no está en la imagen 1
        imagenSuma.escribirPixel(clave[0], clave[1], imagen2.leerPixel(clave[0], clave[1])) #Escribo directamente
    return imagenSuma #Retornamos el valor de la suma

In [ ]:
imagen1 = MatrizDePixelsDict(10,10)
imagen1.escribirPixel(2,3,5)
imagen1.escribirPixel(4,1,10)
imagen2 = MatrizDePixelsDict(10,10)
imagen2.escribirPixel(4,1,2)
imagen2.escribirPixel(5,5,20)


print(imagen1)
print(imagen2)

suma = imagen1 + imagen2
print(suma)

{((2, 3), 5), ((4, 1), 10)} (10, 10)
{((5, 5), 20), ((4, 1), 2)} (10, 10)
{((2, 3), 5), ((5, 5), 20), ((4, 1), 12)} (10, 10)


In [1]:
imagen1 = MatrizDePixelsDict(10000000000,1000000000000)
imagen2 = MatrizDePixelsDict(10000000000,1000000000000)
imagen3 = imagen1 + imagen2

NameError: name 'MatrizDePixelsDict' is not defined

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(imagen1)) #Acá vemos la magia de colab que nos dice que pesa lo mismo pero sabemos que no es así
print(sys.getsizeof(miImagen))

56
56
